version: '3.7'

services:
  client:
    container_name: client
    hostname: client
    build: .
    volumes:
      - "./client:/app"
    ports:
      - "3031:3000"
      - "9221:9229"
    depends_on:
      - api
    command: bash -c "npm start"

  api:
    container_name: api
    hostname: api
    build: .
    volumes:
      - "./api:/app"
    ports:
      - "3003:3000"
      - "9220:9229"
    depends_on:
      - db
    command: bash -c "npm install && npm start"

  db:
    image: mysql:5.7
    container_name: db
    hostname: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: test
      MYSQL_PASSWORD: test1234
    ports:
      - "3307:3306"
    volumes:
      - ./docker/data/db:/var/lib/mysql